### PR TITLE
original search fix

### PR DESCRIPTION
**Pull request by bla0r**
this commit fixes the original search and comin' up with the following options:

- IMDB_EXACT_SEARCH = true
- IMDB_USE_SENSITIVITY = false (highest match will returned)

### CODE REVIEW

**Comment by FabianBeiner** [comment]
Thanks, @bla0r. :) However, before I merge: 

Wouldn't it make more sense to only have one of those options? E.g., only the “exact search” one and the other as fall back? Because I'm pretty sure someone will get confused and disable or enable both.

**Comment by bla0r** [comment]
yeah makes sense. will do it.

**Comment by bla0r** [comment]
fixed :-)

**Comment by FabianBeiner** [comment]
Thanks!

**Pull request merged**
