### PR TITLE
Fix scrapping of locations data

### PR DESCRIPTION
**Pull request by defro**
Hello,

List of all locations don't work anymore so I fix it.

### CODE REVIEW

**Comment by FabianBeiner** [comment]
Thanks!

**Comment by defro** [comment]
> Thanks!

You're welcome. It's a pleasure.

Please @FabianBeiner can you create a new release si I can access to "locations" through composer.

Regards,
Joël

**Comment by bla0r** [comment]
this commit will not fix the issue to grab all locations, because IMDB is using graphQL.

**Comment by FabianBeiner** [comment]
That's fine. We use whatever IMDb posts on the “original” page. :)

**Pull request merged**
