### PR TITLE
Added some new functions.

### PR DESCRIPTION
**Pull request by jmartin82**
Added getAkas function.
Added isReleased function.
Added new helper function IMDBHelper::arrayOutput. This function allow users select the desired output format for calls with multiple results. (string or array)

I sent a very similar pull request some time ago, just now I updated my fork.
Don't hesitate to get all you want from my code.

Cheers

### CODE REVIEW

**Comment by FabianBeiner** [comment]
Holy guacamole! I totally missed this pull request. I most likely won't have time to check your changes the next two weeks, but now I'll remember. ;)

**Comment by FabianBeiner** [comment]
Oh, and while we're at it, @jmartin82: Please keep the LICENSE file and all my copyright notices etc. in your repository.

**Comment by TimmyToole** [comment]
Lol, such ass**le that takes more time to check his credits rather than having his own repo updated. 
By the way, i checked @jmartin82 repo and all your precious credits still there: https://github.com/FabianBeiner/PHP-IMDB-Grabber/blob/master/LICENSE

**Comment by FabianBeiner** [comment]
@TimmyToole Well, thank you. :+1: It’s too late to teach you manners, but I’ll at least teach you how to use the interwebs: You actually linked to **my** (= the asshole’s) repository. If you click on https://github.com/jmartin82/PHP-IMDB-Grabber (you’ll manage the click yourself, won’t you?), you might notice that there is neither a LICENSE file anymore nor my copyright (only a notice “Based on Fabian Beiner (mail@fabian-beiner.de)”). And now the fun part of the MIT license: 

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

(This, by the way, is why I love doing Open Source work.)

**Comment by jmartin82** [comment]
Hi! I don't want add more controversy into this thread. I just added a LICENSE into my test/working branch called "custom" but I never deleted your license file from master branch and I sent to you a pull request form master, you can see that in commit log (not any file has been deleted).

**Comment by FabianBeiner** [comment]
Thanks.

**Pull request merged**
